# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 01:22
from __future__ import unicode_literals

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import pagina.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True)),
                ('slug_tipo', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='tipo')),
                ('descripccion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ('tipo', 'fecha_publicacion'),
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('slug_titulo', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='titulo', unique=True)),
                ('imagen', models.ImageField(blank=True, upload_to=pagina.models.get_upload_pagina_file_name)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('resumen', models.TextField(default='Escribe un resumen')),
                ('cuerpo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('clasificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.Clasificacion')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ('clasificacion', 'fecha_publicacion'),
            },
        ),
    ]
