"""
Django settings for web project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from pathlib import Path
from .get_env import get_env_variable

SITE_ID=1

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

SETTINGS_PATH = Path(__file__)
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = str(SETTINGS_PATH.resolve().parent.parent.parent)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

import sys

#add apps to path
sys.path.append(os.path.join(BASE_DIR, 'apps'))

# Application definition

INSTALLED_APPS = [
    # admin tools
    # https://django-admin-tools.readthedocs.io/en/latest/index.html
    'admin_tools',
    'admin_tools.theming',
    'admin_tools.menu',
    'admin_tools.dashboard',
    #APPS BASE
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ckeditor:
    # https://github.com/django-ckeditor/django-ckeditor
    'ckeditor',
    # uploader
    'ckeditor_uploader',
    'djangobower',
    # Django extensions
    # http://django-extensions.readthedocs.io/en/latest/installation_instructions.html
    'django_extensions',
    # Django Compressor
    # https://django-compressor.readthedocs.io/en/latest/quickstart/
    "compressor",
    #jango imagekit
    'imagekit',
    #phonenumberfield
    'phonenumber_field',
    #APPSS
    'contactform',
    'pagina',
    'actividad',
    'participante'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web.urls'


FILES_DIR = os.path.join(BASE_DIR, 'files')

PROJECTS_DIR = os.path.join(BASE_DIR, 'apps')

TEMPLATES_DIR=[
    os.path.join(FILES_DIR, "templates"),
    #os.path.join(PROJECTS_DIR,'client_profile/templates')
]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATES_DIR,
        #'APP_DIRS': True, commented if loaders exists
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'broker.context_processors.site_data',
            ],
            'loaders':[
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
                'admin_tools.template_loaders.Loader'
            ]
        },
    },
]

WSGI_APPLICATION = 'web.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Session configuration
SESSION_ENGINE="django.contrib.sessions.backends.cache"
SESSION_EXPIRE_AT_BROWSER_CLOSE=True
SESSION_COOKIE_AGE=72000 


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es-CL'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
    'compressor.finders.CompressorFinder',
]

BOWER_COMPONENTS_ROOT = os.path.normpath(os.path.join(FILES_DIR, "components"))

BOWER_INSTALLED_APPS = (
    'underscore',
)


STATIC_ROOT = os.path.normpath(os.path.join(FILES_DIR, "static"))

MEDIA_ROOT = os.path.normpath(os.path.join(FILES_DIR, "media"))

print(STATIC_ROOT)

# Template values
SITE_NAME = "Uniendo Resistencias"
META_DESCRIPTION = "Las herramientas digitales al servicio del moivimiento \
social-ambiental latinoamericanos"

# Configuracion CKEDITOR

CKEDITOR_UPLOAD_SLUGIFY_FILENAME = True
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_BROWSE_SHOW_DIRS = True

# Upload path
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_CONFIGS = {
    'default': {
        'removePlugins': 'stylesheetparser', 'bbcode'
        'toolbar': None,
        'height': 500,
        'width': 900,
        'tabSpaces': 4,
        'allowedContent': True,
        'extraPlugins': ','.join(
            [
                # you extra plugins here
                'ajax',
                'div',
                'autolink',
                'autoembed',
                'embedsemantic',
                'autogrow',
                # 'devtools',code,
                'image',
                'widget',
                'lineutils',
                'clipboard',
                'dialog',
                'dialogui',
                'codesnippetgeshi',
                'elementspath',
                'table',
                'tableresize',
                'tabletools',
                'templates',
                'uicolor',
                'uploadimage',
                'uploadwidget',
                'mathjax',
                'pagebreak',
                'placeholder'
            ]),
    },
}

DATE_INPUT_FORMATS = ['%d/%m/%Y', '%d %m %Y', '%d-%m-%Y']

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.BCryptPasswordHasher',
]

AUTH_PASSWORD_VALIDATORS=[
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


