# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:54
from __future__ import unicode_literals

import actividad.models
import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug_nombre', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='nombre', unique=True)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, upload_to=actividad.models.get_upload_pagina_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True)),
                ('slug_tipo', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='tipo')),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.Clasificacion'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='lugar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.Lugar'),
        ),
    ]
