# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('fono', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('ORG', 'Organizadora'), ('EXP', 'Expositora'), ('PRT', 'Participante')], default='PRT', max_length=3)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ('nombre', 'categoria'),
            },
        ),
    ]
